import Provider from "@/components/SessionProvider";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { getServerSession } from "next-auth";
import { Theme } from "@radix-ui/themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="w-full">
        <Theme>
          <Provider session={session}>{children}</Provider>
        </Theme>
      </body>
    </html>
  );
}
